Task Tracker CLI: TaskManager Class Reference
TaskManager Class Reference
Forward declaration for use in using declarations.
#include <task_manager.h>
Public Member Functions
TaskAddResult addTask (const std::string &title, const std::string &description="")
Add a new task to the collection.
template<std::predicate< const Task & > Predicate>
auto filterTasks (Predicate &&pred) const
Filter tasks using a predicate.
template<typename Self>
auto getAllTasks (this Self &&self) -> decltype(auto)
Get all tasks in the collection.
template<typename Compare>
requires std::strict_weak_order<Compare, Task, Task>
std::vector< Task > getSortedTasks (Compare &&comp) const
Get tasks sorted by custom criteria.
TaskOptional getTask (int id)
Get a task by its ID.
template<typename Self>
auto getTaskByIndex (this Self &&self, size_t index) -> decltype(auto)
Access a task by its index in the collection.
template<typename Self>
auto getTaskCount (this Self &&self) -> size_t
Get the number of tasks in the collection.
auto getTasksByPriority (int min_priority, int max_priority) const
Get tasks filtered by priority range.
auto getTasksByStatus (TaskStatus status) const
Get tasks filtered by status.
TaskResult removeTask (int id)
Remove a task by its ID.
TaskResult updateTaskStatus (int id, TaskStatus status)
Update the status of a task.
Statistics Methods
Methods for calculating task statistics
size_t getCompletedTasksCount () const
Count completed tasks.
size_t getPendingTasksCount () const
Count pending tasks.
double getCompletionRate () const
Calculate task completion rate.
Display Methods
Methods for displaying tasks
void listTasks () const
Display all tasks in the collection.
void listTasksByStatus (TaskStatus status) const
Display tasks filtered by status.
JSON Serialization Methods
Methods for JSON persistence
JsonResult saveToJson (const std::string &filename) const
Save tasks to a JSON file.
JsonResult loadFromJson (const std::string &filename)
Load tasks from a JSON file.
std::string toJsonString () const
Convert tasks to JSON string.
JsonResult fromJsonString (const std::string &json_str)
Parse tasks from JSON string.
Private Attributes
int _next_id = 1
std::vector< Task > _tasks
Detailed Description
Forward declaration for use in using declarations.
Manages a collection of tasks with various operations.
Provides methods for adding, removing, updating, and querying tasks
Definition at line 16 of file task_manager.h.
Member Function Documentation
addTask()
TaskAddResult TaskManager::addTask (const std::string & title, const std::string & description = "")
Add a new task to the collection.
Parameters
title The title of the task
description Optional description of the task
Returns
Task ID on success, or error code on failure
Definition at line 9 of file task_manager.cpp.
{
    if (title.empty()) {
        return std::unexpected(TaskError::EmptyTitle);
    }
    // Check for duplicate titles
    auto existing = std::ranges::find_if(_tasks, [&title](const Task& task) {
        return task.getTitle() == title;
    });
    if (existing != _tasks.end()) {
        return std::unexpected(TaskError::DuplicateTask);
    }
    int new_id = _next_id++;
    _tasks.emplace_back(new_id, title, description);
    return new_id;  // C++23: Return the ID of the newly created task
}
References _next_id, _tasks, DuplicateTask, EmptyTitle, and Task::getTitle().
filterTasks()
template<std::predicate< const Task & > Predicate> auto TaskManager::filterTasks (Predicate && pred) const inline
Filter tasks using a predicate.
Template Parameters
Predicate Function type that takes a Task and returns bool
Parameters
pred Predicate function for filtering
Returns
Range of tasks that satisfy the predicate
Definition at line 59 of file task_manager.h.
{
        return _tasks | std::views::filter(std::forward<Predicate>(pred));
    }
References _tasks.
Referenced by getTasksByPriority(), and getTasksByStatus().
fromJsonString()
JsonResult TaskManager::fromJsonString (const std::string & json_str)
Parse tasks from JSON string.
Parameters
json_str JSON string to parse
Returns
Success or error code
Definition at line 189 of file task_manager.cpp.
{
    try {
        // Simple JSON parsing - extract next_id and tasks array
        auto findValue = [&json_str](const std::string& key) -> std::string {
            std::string search_key = "\"" + key + "\":";
            size_t pos = json_str.find(search_key);
            if (pos == std::string::npos) return "";
            pos += search_key.length();
            while (pos < json_str.length() && std::isspace(json_str[pos])) ++pos;
            if (pos >= json_str.length()) return "";
            if (json_str[pos] == '"') {
                // String value
                ++pos;
                size_t end_pos = pos;
                while (end_pos < json_str.length() && json_str[end_pos] != '"') {
                    if (json_str[end_pos] == '\\') ++end_pos; // Skip escaped characters
                    ++end_pos;
                }
                return json_str.substr(pos, end_pos - pos);
            } else {
                // Number or other value
                size_t end_pos = pos;
                while (end_pos < json_str.length() &&
                       json_str[end_pos] != ',' &&
                       json_str[end_pos] != '}' &&
                       json_str[end_pos] != '\n' &&
                       json_str[end_pos] != '\r') {
                    ++end_pos;
                }
                std::string value = json_str.substr(pos, end_pos - pos);
                // Trim whitespace
                value.erase(0, value.find_first_not_of(" \t\n\r"));
                value.erase(value.find_last_not_of(" \t\n\r") + 1);
                return value;
            }
        };
        std::string next_id_str = findValue("next_id");
        if (!next_id_str.empty()) {
            _next_id = std::stoi(next_id_str);
        }
        // Find tasks array
        size_t tasks_pos = json_str.find("\"tasks\":");
        if (tasks_pos == std::string::npos) {
            return std::unexpected(JsonError::InvalidFormat);
        }
        size_t array_start = json_str.find("[", tasks_pos);
        if (array_start == std::string::npos) {
            return std::unexpected(JsonError::InvalidFormat);
        }
        size_t array_end = json_str.find("]", array_start);
        if (array_end == std::string::npos) {
            return std::unexpected(JsonError::InvalidFormat);
        }
        // Parse individual task objects
        _tasks.clear();
        size_t pos = array_start + 1;
        while (pos < array_end) {
            // Find next task object
            size_t obj_start = json_str.find("{", pos);
            if (obj_start >= array_end) break;
            // Find matching closing brace
            size_t obj_end = obj_start + 1;
            int brace_count = 1;
            while (obj_end < array_end && brace_count > 0) {
                if (json_str[obj_end] == '{') ++brace_count;
                else if (json_str[obj_end] == '}') --brace_count;
                ++obj_end;
            }
            if (brace_count == 0) {
                std::string task_json = json_str.substr(obj_start, obj_end - obj_start);
                auto task_result = Task::fromJson(task_json);
                if (task_result) {
                    _tasks.push_back(*task_result);
                } else {
                    return std::unexpected(task_result.error());
                }
            }
            pos = obj_end;
        }
        return true;
    } catch (const std::exception&) {
        return std::unexpected(JsonError::ParseError);
    }
}
References _next_id, _tasks, Task::fromJson(), InvalidFormat, and ParseError.
Referenced by loadFromJson().
getAllTasks()
template<typename Self> auto TaskManager::getAllTasks (this Self && self) -> decltype(auto) inline
Get all tasks in the collection.
C++23: Uses deducing this for const/non-const resolution
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the tasks vector
Definition at line 119 of file task_manager.h.
{
        return (std::forward<Self>(self)._tasks);
    }
References _tasks.
getCompletedTasksCount()
size_t TaskManager::getCompletedTasksCount () const
Count completed tasks.
Returns
Number of completed tasks
Definition at line 65 of file task_manager.cpp.
{
    return std::ranges::count_if(_tasks, [](const Task& task) {
        return task.isCompleted();
    });
}
References _tasks, and Task::isCompleted().
Referenced by getCompletionRate().
getCompletionRate()
double TaskManager::getCompletionRate () const
Calculate task completion rate.
Returns
Percentage of completed tasks
Definition at line 77 of file task_manager.cpp.
{
    if (_tasks.empty()) return 0.0;
    return static_cast<double>(getCompletedTasksCount()) / _tasks.size() * 100.0;
}
References _tasks, and getCompletedTasksCount().
Referenced by listTasks().
getPendingTasksCount()
size_t TaskManager::getPendingTasksCount () const
Count pending tasks.
Returns
Number of pending tasks
Definition at line 71 of file task_manager.cpp.
{
    return std::ranges::count_if(_tasks, [](const Task& task) {
        return task.getStatus() == TaskStatus::Pending;
    });
}
References _tasks, Task::getStatus(), and Pending.
getSortedTasks()
template<typename Compare> requires std::strict_weak_order<Compare, Task, Task> std::vector< Task > TaskManager::getSortedTasks (Compare && comp) const inline
Get tasks sorted by custom criteria.
Template Parameters
Compare Comparison function type
Parameters
comp Comparison function for sorting
Returns
Vector of tasks sorted according to comparator
Definition at line 95 of file task_manager.h.
{
        auto sorted_tasks = _tasks;
        std::ranges::sort(sorted_tasks, std::forward<Compare>(comp));
        return sorted_tasks;
    }
References _tasks.
getTask()
TaskOptional TaskManager::getTask (int id)
Get a task by its ID.
Parameters
id The ID of the task to retrieve
Returns
Task object or error code if not found
Definition at line 41 of file task_manager.cpp.
{
    auto it = std::ranges::find_if(_tasks, [id](const Task& task) {
        return task.getId() == id;
    });
    if (it == _tasks.end()) {
        return std::unexpected(TaskError::TaskNotFound);
    }
    return *it;
}
References _tasks, Task::getId(), and TaskNotFound.
getTaskByIndex()
template<typename Self> auto TaskManager::getTaskByIndex (this Self && self, size_t index) -> decltype(auto) inline
Access a task by its index in the collection.
C++23: Uses deducing this for const/non-const resolution
Template Parameters
Self Deduced self type (const or non-const)
Parameters
index Position of the task in the collection
Returns
Reference to the task
Exceptions
std::out_of_range if index is out of bounds
Definition at line 132 of file task_manager.h.
{
        if (index >= self._tasks.size()) {
            throw std::out_of_range("Task index out of range");
        }
        return (std::forward<Self>(self)._tasks[index]);
    }
References _tasks.
getTaskCount()
template<typename Self> auto TaskManager::getTaskCount (this Self && self) -> size_t inline
Get the number of tasks in the collection.
C++23: Uses deducing this for const/non-const resolution
Template Parameters
Self Deduced self type (const or non-const)
Returns
Number of tasks
Definition at line 108 of file task_manager.h.
{
        return self._tasks.size();
    }
getTasksByPriority()
auto TaskManager::getTasksByPriority (int min_priority, int max_priority) const inline
Get tasks filtered by priority range.
Parameters
min_priority Minimum priority (inclusive)
max_priority Maximum priority (inclusive)
Returns
Range of tasks within the priority range
Definition at line 80 of file task_manager.h.
{
        return filterTasks([min_priority, max_priority](const Task& task) {
            int priority = task.getMetadata().priority;
            return priority >= min_priority && priority <= max_priority;
        });
    }
References filterTasks(), and Task::getMetadata().
getTasksByStatus()
auto TaskManager::getTasksByStatus (TaskStatus status) const inline
Get tasks filtered by status.
Parameters
status Status to filter by
Returns
Range of tasks with the specified status
Definition at line 68 of file task_manager.h.
{
        return filterTasks([status](const Task& task) {
            return task.getStatus() == status;
        });
    }
References filterTasks(), and Task::getStatus().
Referenced by listTasksByStatus().
listTasks()
void TaskManager::listTasks () const
Display all tasks in the collection.
Definition at line 82 of file task_manager.cpp.
{
    if (_tasks.empty()) {
        std::print("No tasks available.\n");
        return;
    }
    std::print("=== Task List ({} tasks) ===\n", _tasks.size());
    for (const auto& task : _tasks) {
        std::print("[{}] {} - {} (Priority: {}, Category: {})\n",
                    task.getId(),
                    task.getTitle(),
                    taskStatusToString(task.getStatus()),
                    task.getMetadata().priority,
                    task.getMetadata().category);
    }
    std::print("Completion Rate: {:.1f}%\n", getCompletionRate());
}
References _tasks, getCompletionRate(), and taskStatusToString().
listTasksByStatus()
void TaskManager::listTasksByStatus (TaskStatus status) const
Display tasks filtered by status.
Parameters
status Status to filter by
Definition at line 100 of file task_manager.cpp.
{
    auto filtered_tasks = getTasksByStatus(status);
    auto task_vector = std::vector<Task>(filtered_tasks.begin(), filtered_tasks.end());
    if (task_vector.empty()) {
        std::print("No tasks with status: {}\n", taskStatusToString(status));
        return;
    }
    std::print("=== {} Tasks ({} tasks) ===\n",
                taskStatusToString(status), task_vector.size());
    for (const auto& task : task_vector) {
        std::print("[{}] {} (Priority: {}, Category: {})\n",
                    task.getId(),
                    task.getTitle(),
                    taskStatusToString(task.getStatus()),
                    task.getMetadata().priority,
                    task.getMetadata().category);
    }
}
References getTasksByStatus(), and taskStatusToString().
loadFromJson()
JsonResult TaskManager::loadFromJson (const std::string & filename)
Load tasks from a JSON file.
Parameters
filename Path to the input file
Returns
Success or error code
Definition at line 172 of file task_manager.cpp.
{
    try {
        std::ifstream file(filename);
        if (!file.is_open()) {
            return std::unexpected(JsonError::FileNotFound);
        }
        std::ostringstream buffer;
        buffer << file.rdbuf();
        std::string json_content = buffer.str();
        return fromJsonString(json_content);
    } catch (const std::exception&) {
        return std::unexpected(JsonError::ParseError);
    }
}
References FileNotFound, fromJsonString(), and ParseError.
removeTask()
TaskResult TaskManager::removeTask (int id)
Remove a task by its ID.
Parameters
id The ID of the task to remove
Returns
Success or error code
Definition at line 28 of file task_manager.cpp.
{
    auto it = std::ranges::find_if(_tasks, [id](const Task& task) {
        return task.getId() == id;
    });
    if (it == _tasks.end()) {
        return std::unexpected(TaskError::TaskNotFound);
    }
    _tasks.erase(it);
    return true;
}
References _tasks, Task::getId(), and TaskNotFound.
saveToJson()
JsonResult TaskManager::saveToJson (const std::string & filename) const
Save tasks to a JSON file.
Parameters
filename Path to the output file
Returns
Success or error code
Definition at line 152 of file task_manager.cpp.
{
    try {
        std::ofstream file(filename);
        if (!file.is_open()) {
            return std::unexpected(JsonError::FileNotFound);
        }
        std::string json_content = toJsonString();
        file << json_content;
        if (file.fail()) {
            return std::unexpected(JsonError::WriteError);
        }
        return true;
    } catch (const std::exception&) {
        return std::unexpected(JsonError::WriteError);
    }
}
References FileNotFound, toJsonString(), and WriteError.
toJsonString()
std::string TaskManager::toJsonString () const
Convert tasks to JSON string.
Returns
JSON representation of all tasks
Definition at line 122 of file task_manager.cpp.
{
    std::ostringstream json;
    json << "{\n";
    json << std::format("  \"version\": \"1.0\",\n");
    json << std::format("  \"next_id\": {},\n", _next_id);
    json << "  \"tasks\": [\n";
    for (size_t i = 0; i < _tasks.size(); ++i) {
        std::string task_json = _tasks[i].toJson();
        // Indent the task JSON
        std::istringstream task_stream(task_json);
        std::string line;
        bool first_line = true;
        while (std::getline(task_stream, line)) {
            if (!first_line) json << "\n";
            json << "    " << line;
            first_line = false;
        }
        if (i < _tasks.size() - 1) {
            json << ",";
        }
        json << "\n";
    }
    json << "  ]\n";
    json << "}";
    return json.str();
}
References _next_id, and _tasks.
Referenced by saveToJson().
updateTaskStatus()
TaskResult TaskManager::updateTaskStatus (int id, TaskStatus status)
Update the status of a task.
Parameters
id The ID of the task to update
status The new status to set
Returns
Success or error code
Definition at line 53 of file task_manager.cpp.
{
    auto it = std::ranges::find_if(_tasks, [id](Task& task) {
        return task.getId() == id;
    });
    if (it == _tasks.end()) {
        return std::unexpected(TaskError::TaskNotFound);
    }
    return it->setStatus(status);
}
References _tasks, Task::getId(), and TaskNotFound.
Member Data Documentation
_next_id
int TaskManager::_next_id = 1 private
Next available task ID
Definition at line 19 of file task_manager.h.
Referenced by addTask(), fromJsonString(), and toJsonString().
_tasks
std::vector<Task> TaskManager::_tasks private
Collection of all tasks
Definition at line 18 of file task_manager.h.
Referenced by addTask(), filterTasks(), fromJsonString(), getAllTasks(), getCompletedTasksCount(), getCompletionRate(), getPendingTasksCount(), getSortedTasks(), getTask(), getTaskByIndex(), listTasks(), removeTask(), toJsonString(), and updateTaskStatus().
The documentation for this class was generated from the following files:
task_manager.h
task_manager.cpp