Task Tracker CLI: Task Class Reference
Task Class Reference
Represents a task with its properties and metadata.
#include <task.h>
Public Member Functions
Task (int id, std::string title, std::string description="", TaskStatus status=TaskStatus::Pending)
Constructs a new Task object.
std::chrono::duration< double > getAge () const
Get the age of the task.
template<typename Self>
auto getDescription (this Self &&self) -> decltype(auto)
Get the task's description.
template<typename Self>
auto getId (this Self &&self) -> decltype(auto)
Get the task's unique ID.
template<typename Self>
auto getMetadata (this Self &&self) -> decltype(auto)
Get the task's metadata.
template<typename Self>
auto getStatus (this Self &&self) -> decltype(auto)
Get the task's status.
template<typename Self>
auto getTitle (this Self &&self) -> decltype(auto)
Get the task's title.
bool isCompleted () const
Check if the task is completed.
void markCompleted ()
Mark the task as completed.
bool operator< (const Task &other) const
Less-than comparison operator.
bool operator== (const Task &other) const
Equality comparison operator.
TaskResult setCategory (const std::string &category)
Set the task's category.
TaskResult setDescription (const std::string &description)
Set the task's description.
TaskResult setPriority (int priority)
Set the task's priority.
TaskResult setStatus (TaskStatus status)
Set the task's status.
TaskResult setTitle (const std::string &title)
Set the task's title.
std::string to_string () const
Get a string representation of the task.
std::string toJson () const
Convert the task to JSON format.
Static Public Member Functions
static std::expected< Task, JsonError > fromJson (const std::string &json_str)
Create a Task from a JSON string.
Private Attributes
std::string _description
Detailed description of the task.
int _id
Unique identifier for the task.
TaskMetadata _metadata
Metadata for the task.
TaskStatus _status
Current status of the task.
std::string _title
Title of the task.
Detailed Description
Represents a task with its properties and metadata.
Core class for the task tracking application, demonstrating C++23 features
Definition at line 158 of file task.h.
Constructor & Destructor Documentation
Task()
Task::Task (int id, std::string title, std::string description = "", TaskStatus status = TaskStatus::Pending)
Constructs a new Task object.
Constructs a Task object with specified properties.
Parameters
id Unique identifier for the task
title Title of the task
description Description of the task (optional)
status Initial status of the task (default: Pending)
id Unique identifier for the task
title Title of the task
description Description of the task
status Initial status of the task
Definition at line 21 of file task.cpp.
    : _id(id), _title(std::move(title)), _description(std::move(description)), _status(status) {
    auto now = std::chrono::system_clock::now();
    _metadata.created_at = now;
    _metadata.updated_at = now;
    _metadata.category = "General";
}
References _description, _id, _metadata, _status, and _title.
Referenced by fromJson(), operator<(), and operator==().
Member Function Documentation
fromJson()
std::expected< Task, JsonError > Task::fromJson (const std::string & json_str) static
Create a Task from a JSON string.
Parameters
json_str JSON string to parse
Returns
Task object if successful, or JsonError if parsing failed
Parameters
json_str JSON string to parse
Returns
Task object if successful, or JsonError if parsing failed
C++23 Feature: Uses std::expected for error handling
Definition at line 302 of file task.cpp.
{
    try {
        // Simple JSON parsing - in production, use a proper JSON library
        auto findValue = [&json_str](const std::string& key) -> std::string {
            std::string search_key = "\"" + key + "\":";
            size_t pos = json_str.find(search_key);
            if (pos == std::string::npos) return "";
            pos += search_key.length();
            while (pos < json_str.length() && std::isspace(json_str[pos])) ++pos;
            if (pos >= json_str.length()) return "";
            if (json_str[pos] == '"') {
                // String value
                ++pos;
                size_t end_pos = pos;
                while (end_pos < json_str.length() && json_str[end_pos] != '"') {
                    if (json_str[end_pos] == '\\') ++end_pos; // Skip escaped characters
                    ++end_pos;
                }
                return unescapeJsonString(json_str.substr(pos, end_pos - pos));
            } else {
                // Number or other value
                size_t end_pos = pos;
                while (end_pos < json_str.length() &&
                       json_str[end_pos] != ',' &&
                       json_str[end_pos] != '}' &&
                       json_str[end_pos] != '\n' &&
                       json_str[end_pos] != '\r') {
                    ++end_pos;
                }
                std::string value = json_str.substr(pos, end_pos - pos);
                // Trim whitespace
                value.erase(0, value.find_first_not_of(" \t\n\r"));
                value.erase(value.find_last_not_of(" \t\n\r") + 1);
                return value;
            }
        };
        std::string id_str = findValue("id");
        std::string title = findValue("title");
        std::string description = findValue("description");
        std::string status_str = findValue("status");
        std::string category = findValue("category");
        std::string priority_str = findValue("priority");
        std::string created_at_str = findValue("created_at");
        std::string updated_at_str = findValue("updated_at");
        std::string completed_at_str = findValue("completed_at");
        if (id_str.empty() || title.empty()) {
            return std::unexpected(JsonError::InvalidFormat);
        }
        int id = std::stoi(id_str);
        auto status_opt = stringToTaskStatus(status_str);
        if (!status_opt) {
            return std::unexpected(JsonError::InvalidFormat);
        }
        Task task(id, title, description, *status_opt);
        if (!category.empty()) {
            task.setCategory(category);
        }
        if (!priority_str.empty()) {
            int priority = std::stoi(priority_str);
            task.setPriority(priority);
        }
        if (!created_at_str.empty()) {
            task._metadata.created_at = isoStringToTimePoint(created_at_str);
        }
        if (!updated_at_str.empty()) {
            task._metadata.updated_at = isoStringToTimePoint(updated_at_str);
        }
        if (!completed_at_str.empty()) {
            task._metadata.completed_at = isoStringToTimePoint(completed_at_str);
        }
        return task;
    } catch (const std::exception&) {
        return std::unexpected(JsonError::ParseError);
    }
}
References Task(), _metadata, TaskMetadata::completed_at, TaskMetadata::created_at, InvalidFormat, isoStringToTimePoint(), ParseError, setCategory(), setPriority(), stringToTaskStatus(), unescapeJsonString(), and TaskMetadata::updated_at.
Referenced by TaskManager::fromJsonString().
getAge()
std::chrono::duration< double > Task::getAge () const
Get the age of the task.
Calculate the age of the task.
Returns
Duration since the task was created
Duration since task creation
Definition at line 138 of file task.cpp.
{
    return std::chrono::system_clock::now() - _metadata.created_at;
}
References _metadata.
getDescription()
template<typename Self> auto Task::getDescription (this Self && self) -> decltype(auto) inline
Get the task's description.
C++23 Feature: Deducing this
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the task's description
Definition at line 206 of file task.h.
{
        return (std::forward<Self>(self)._description);
    }
References _description.
getId()
template<typename Self> auto Task::getId (this Self && self) -> decltype(auto) inline
Get the task's unique ID.
C++23 Feature: Deducing this - eliminates const/non-const duplication
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the task's ID
Definition at line 184 of file task.h.
{
        return (std::forward<Self>(self)._id);
    }
References _id.
Referenced by TaskManager::getTask(), App::handleSort(), TaskManager::removeTask(), and TaskManager::updateTaskStatus().
getMetadata()
template<typename Self> auto Task::getMetadata (this Self && self) -> decltype(auto) inline
Get the task's metadata.
C++23 Feature: Deducing this
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the task's metadata
Definition at line 228 of file task.h.
{
        return (std::forward<Self>(self)._metadata);
    }
References _metadata.
Referenced by TaskMatrix::addTask(), and TaskManager::getTasksByPriority().
getStatus()
template<typename Self> auto Task::getStatus (this Self && self) -> decltype(auto) inline
Get the task's status.
C++23 Feature: Deducing this
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the task's status
Definition at line 217 of file task.h.
{
        return (std::forward<Self>(self)._status);
    }
References _status.
Referenced by TaskManager::getPendingTasksCount(), TaskManager::getTasksByStatus(), and App::handleSort().
getTitle()
template<typename Self> auto Task::getTitle (this Self && self) -> decltype(auto) inline
Get the task's title.
C++23 Feature: Deducing this
Template Parameters
Self Deduced self type (const or non-const)
Returns
Reference to the task's title
Definition at line 195 of file task.h.
{
        return (std::forward<Self>(self)._title);
    }
References _title.
Referenced by TaskManager::addTask(), and App::handleSort().
isCompleted()
bool Task::isCompleted () const
Check if the task is completed.
Returns
true if the task status is Completed
Definition at line 130 of file task.cpp.
{
    return _status == TaskStatus::Completed;
}
References _status, and Completed.
Referenced by TaskManager::getCompletedTasksCount().
markCompleted()
void Task::markCompleted ()
Mark the task as completed.
Sets status to Completed and updates completed_at timestamp
Definition at line 146 of file task.cpp.
{
    setStatus(TaskStatus::Completed);
}
References Completed, and setStatus().
operator<()
bool Task::operator< (const Task & other) const inline
Less-than comparison operator.
Parameters
other The task to compare with
Returns
true if this task is less than the other
Definition at line 287 of file task.h.
{
        if (_id != other._id) return _id < other._id;
        if (_title != other._title) return _title < other._title;
        return static_cast<int>(_status) < static_cast<int>(other._status);
    }
References Task(), _id, _status, and _title.
operator==()
bool Task::operator== (const Task & other) const inline
Equality comparison operator.
Parameters
other The task to compare with
Returns
true if the tasks are equal
Definition at line 278 of file task.h.
{
        return _id == other._id && _title == other._title && _status == other._status;
    }
References Task(), _id, _status, and _title.
setCategory()
TaskResult Task::setCategory (const std::string & category)
Set the task's category.
Sets the task's category.
Parameters
category New category for the task
Returns
TaskResult indicating success or the reason for failure
Parameters
category New category for the task
Returns
TaskResult with success
Definition at line 92 of file task.cpp.
{
    _metadata.category = category;
    _metadata.updated_at = std::chrono::system_clock::now();
    return true;
}
References _metadata.
Referenced by fromJson().
setDescription()
TaskResult Task::setDescription (const std::string & description)
Set the task's description.
Sets the task's description.
Parameters
description New description for the task
Returns
TaskResult indicating success or the reason for failure
Parameters
description New description for the task
Returns
TaskResult with success
Definition at line 48 of file task.cpp.
{
    _description = description;
    _metadata.updated_at = std::chrono::system_clock::now();
    return true;
}
References _description, and _metadata.
setPriority()
TaskResult Task::setPriority (int priority)
Set the task's priority.
Sets the task's priority.
Parameters
priority New priority for the task (0-10)
Returns
TaskResult indicating success or the reason for failure
Parameters
priority New priority for the task (0-10)
Returns
TaskResult with success or error if priority is invalid
Definition at line 76 of file task.cpp.
{
    // Validate priority range (0-10)
    if (priority < 0 || priority > 10) {
        return std::unexpected(TaskError::InvalidPriority);
    }
    _metadata.priority = priority;
    _metadata.updated_at = std::chrono::system_clock::now();
    return true;
}
References _metadata, and InvalidPriority.
Referenced by fromJson().
setStatus()
TaskResult Task::setStatus (TaskStatus status)
Set the task's status.
Sets the task's status.
Parameters
status New status for the task
Returns
TaskResult indicating success or the reason for failure
Parameters
status New status for the task
Returns
TaskResult with success
If status is Completed, also sets the completed_at timestamp
Definition at line 60 of file task.cpp.
{
    _status = status;
    _metadata.updated_at = std::chrono::system_clock::now();
    if (status == TaskStatus::Completed) {
        _metadata.completed_at = std::chrono::system_clock::now();
    }
    return true;
}
References _metadata, _status, and Completed.
Referenced by markCompleted().
setTitle()
TaskResult Task::setTitle (const std::string & title)
Set the task's title.
Sets the task's title.
Parameters
title New title for the task
Returns
TaskResult indicating success or the reason for failure
Parameters
title New title for the task
Returns
TaskResult with success or error
Definition at line 34 of file task.cpp.
{
    if (title.empty()) {
        return std::unexpected(TaskError::EmptyTitle);
    }
    _title = title;
    _metadata.updated_at = std::chrono::system_clock::now();
    return true;
}
References _metadata, _title, and EmptyTitle.
to_string()
std::string Task::to_string () const
Get a string representation of the task.
Creates a formatted string representation of the task.
Returns
Formatted string with task details
String containing all task details
Uses C++23 std::format for string formatting
Definition at line 103 of file task.cpp.
{
    // C++23 std::format and std::print usage
    auto created_time = std::chrono::system_clock::to_time_t(_metadata.created_at);
    auto updated_time = std::chrono::system_clock::to_time_t(_metadata.updated_at);
    std::ostringstream oss;
    std::string task_info = std::format("Task [ID: {}]\n", _id);
    task_info += std::format("  Title: {}\n", _title);
    task_info += std::format("  Description: {}\n", _description.empty() ? "None" : _description);
    task_info += std::format("  Status: {}\n", taskStatusToString(_status));
    task_info += std::format("  Category: {}\n", _metadata.category);
    task_info += std::format("  Priority: {}\n", _metadata.priority);
    task_info += std::format("  Created: {:%Y-%m-%d %H:%M:%S}\n", std::chrono::system_clock::from_time_t(created_time));
    task_info += std::format("  Updated: {:%Y-%m-%d %H:%M:%S}\n", std::chrono::system_clock::from_time_t(updated_time));
    if (_metadata.completed_at.has_value()) {
        auto completed_time = std::chrono::system_clock::to_time_t(*_metadata.completed_at);
        task_info += std::format("  Completed: {:%Y-%m-%d %H:%M:%S}\n", std::chrono::system_clock::from_time_t(completed_time));
    }
    return task_info;
}
References _description, _id, _metadata, _status, _title, and taskStatusToString().
toJson()
std::string Task::toJson () const
Convert the task to JSON format.
Convert Task to JSON string representation.
Returns
JSON string representation of the task
Formatted JSON string with all task properties
Uses C++23 std::format for string formatting
Definition at line 276 of file task.cpp.
{
    std::ostringstream json;
    json << "{\n";
    json << std::format("  \"id\": {},\n", _id);
    json << std::format("  \"title\": \"{}\",\n", escapeJsonString(_title));
    json << std::format("  \"description\": \"{}\",\n", escapeJsonString(_description));
    json << std::format("  \"status\": \"{}\",\n", taskStatusToString(_status));
    json << std::format("  \"category\": \"{}\",\n", escapeJsonString(_metadata.category));
    json << std::format("  \"priority\": {},\n", _metadata.priority);
    json << std::format("  \"created_at\": \"{}\",\n", timePointToIsoString(_metadata.created_at));
    json << std::format("  \"updated_at\": \"{}\"", timePointToIsoString(_metadata.updated_at));
    if (_metadata.completed_at.has_value()) {
        json << std::format(",\n  \"completed_at\": \"{}\"", timePointToIsoString(*_metadata.completed_at));
    }
    json << "\n}";
    return json.str();
}
References _description, _id, _metadata, _status, _title, escapeJsonString(), taskStatusToString(), and timePointToIsoString().
Member Data Documentation
_description
std::string Task::_description private
Detailed description of the task.
Definition at line 162 of file task.h.
Referenced by Task(), getDescription(), setDescription(), to_string(), and toJson().
_id
int Task::_id private
Unique identifier for the task.
Definition at line 160 of file task.h.
Referenced by Task(), getId(), operator<(), operator==(), to_string(), and toJson().
_metadata
TaskMetadata Task::_metadata private
Metadata for the task.
Definition at line 164 of file task.h.
Referenced by Task(), fromJson(), getAge(), getMetadata(), setCategory(), setDescription(), setPriority(), setStatus(), setTitle(), to_string(), and toJson().
_status
TaskStatus Task::_status private
Current status of the task.
Definition at line 163 of file task.h.
Referenced by Task(), getStatus(), isCompleted(), operator<(), operator==(), setStatus(), to_string(), and toJson().
_title
std::string Task::_title private
Title of the task.
Definition at line 161 of file task.h.
Referenced by Task(), getTitle(), operator<(), operator==(), setTitle(), to_string(), and toJson().
The documentation for this class was generated from the following files:
task.h
task.cpp