Task Tracker CLI: task.h File Reference
task.h File Reference
Defines the Task class and related utilities for the TaskTracker application.
#include <string>
#include <vector>
#include <chrono>
#include <optional>
#include <expected>
#include <format>
#include <print>
#include <concepts>
#include <ranges>
#include <algorithm>
#include <iostream>
#include <type_traits>
#include <compare>
#include <fstream>
#include <sstream>
Classes
class Task
Represents a task with its properties and metadata.
struct TaskMetadata
Metadata associated with a Task.
Concepts
concept Stringable
Concept requiring a to_string method that returns a string.
concept TaskLike
Concept defining requirements for a Task-like type.
Typedefs
using JsonResult = std::expected<bool, JsonError>
Result type for JSON operations.
using TaskAddResult = std::expected<int, TaskError>
Result type for task creation operations that return the new task's ID.
using TaskOptional = std::expected<class Task, TaskError>
Result type for operations that return a Task or an error.
using TaskResult = std::expected<bool, TaskError>
Result type for task operations that return success/failure.
Enumerations
enum class JsonError { FileNotFound , InvalidFormat , WriteError , ParseError }
Represents possible errors in JSON serialization/deserialization.
enum class TaskError {
InvalidId , TaskNotFound , InvalidStatus , EmptyTitle ,
DuplicateTask , InvalidPriority
}
Represents possible errors in task operations.
enum class TaskStatus : std::uint8_t { Pending , InProgress , Completed , Cancelled }
Represents the status of a task in its lifecycle.
Functions
JsonResult deserializeTaskFromJson (Task &task, const std::string &filePath)
Deserialize a task from a JSON file.
constexpr std::string_view getTaskStatusString (TaskStatus status)
Get string representation of a task status.
consteval bool isValidPriority (int priority)
Validates priority value at compile time.
consteval bool isValidTaskId (int id)
Validates task ID at compile time.
std::string jsonErrorToString (JsonError error)
Convert a JsonError enum to its string representation.
consteval size_t maxTaskDescriptionLength ()
Maximum allowed length for task descriptions.
consteval size_t maxTaskTitleLength ()
Maximum allowed length for task titles.
JsonResult serializeTaskToJson (const Task &task, const std::string &filePath)
Serialize a task to a JSON file.
std::optional< TaskStatus > stringToTaskStatus (const std::string &str)
Convert a string to a TaskStatus enum.
std::string taskErrorToString (TaskError error)
Convert a TaskError enum to its string representation.
std::string taskStatusToString (TaskStatus status)
Convert a TaskStatus enum to its string representation.
std::string unescapeJsonString (const std::string &str)
Unescape a JSON string.
constexpr bool validateTaskData (std::string_view title, std::string_view description, int priority)
Validate task data fields.
Detailed Description
Defines the Task class and related utilities for the TaskTracker application.
This file contains the main Task class, TaskStatus enum, concepts, error types, and utility functions for task management with modern C++23 features.
Definition in file task.h.
Typedef Documentation
JsonResult
using JsonResult = std::expected<bool, JsonError>
Result type for JSON operations.
Definition at line 108 of file task.h.
TaskAddResult
using TaskAddResult = std::expected<int, TaskError>
Result type for task creation operations that return the new task's ID.
C++23 Feature: Returns task ID on success
Definition at line 102 of file task.h.
TaskOptional
using TaskOptional = std::expected<class Task, TaskError>
Result type for operations that return a Task or an error.
Definition at line 95 of file task.h.
TaskResult
using TaskResult = std::expected<bool, TaskError>
Result type for task operations that return success/failure.
C++23 Feature: Uses std::expected for better error handling
Definition at line 89 of file task.h.
Enumeration Type Documentation
JsonError
enum class JsonError strong
Represents possible errors in JSON serialization/deserialization.
Enumerator
FileNotFound
The JSON file could not be opened.
InvalidFormat
The JSON file has an invalid format.
WriteError
Failed to write to the JSON file.
ParseError
Failed to parse the JSON content.
Definition at line 77 of file task.h.
                     {
    FileNotFound,   ///< The JSON file could not be opened
    InvalidFormat,  ///< The JSON file has an invalid format
    WriteError,     ///< Failed to write to the JSON file
    ParseError      ///< Failed to parse the JSON content
};
TaskError
enum class TaskError strong
Represents possible errors in task operations.
Enumerator
InvalidId
The task ID is invalid.
TaskNotFound
The specified task was not found.
InvalidStatus
The task status is invalid.
EmptyTitle
The task title cannot be empty.
DuplicateTask
A task with the same title already exists.
InvalidPriority
The priority value is outside the valid range.
Definition at line 64 of file task.h.
                     {
    InvalidId,       ///< The task ID is invalid
    TaskNotFound,    ///< The specified task was not found
    InvalidStatus,   ///< The task status is invalid
    EmptyTitle,      ///< The task title cannot be empty
    DuplicateTask,   ///< A task with the same title already exists
    InvalidPriority  ///< The priority value is outside the valid range
};
TaskStatus
enum class TaskStatus : std::uint8_t strong
Represents the status of a task in its lifecycle.
Enumerator
Pending
Task is yet to be started.
InProgress
Task is currently being worked on.
Completed
Task has been completed successfully.
Cancelled
Task has been cancelled.
Definition at line 31 of file task.h.
                      : std::uint8_t {
    Pending,     ///< Task is yet to be started
    InProgress,  ///< Task is currently being worked on
    Completed,   ///< Task has been completed successfully
    Cancelled    ///< Task has been cancelled
};
Function Documentation
deserializeTaskFromJson()
JsonResult deserializeTaskFromJson (Task & task, const std::string & filePath)
Deserialize a task from a JSON file.
Parameters
task The task object to populate
filePath Path to the input file
Returns
JsonResult indicating success or the reason for failure
getTaskStatusString()
std::string_view getTaskStatusString (TaskStatus status) constexpr
Get string representation of a task status.
C++23 Feature: if consteval for optimized string processing with different behavior at compile-time vs runtime
Parameters
status The task status to convert
Returns
String view representing the status
Definition at line 427 of file task.h.
{
    if consteval {
        // Compile-time: Simple lookup
        switch (status) {
            case TaskStatus::Pending: return "Pending";
            case TaskStatus::InProgress: return "InProgress";
            case TaskStatus::Completed: return "Completed";
            case TaskStatus::Cancelled: return "Cancelled";
        }
        return "Unknown";
    } else {
        // Runtime: More flexible processing
        switch (status) {
            case TaskStatus::Pending: return " Pending";
            case TaskStatus::InProgress: return " In Progress";
            case TaskStatus::Completed: return " Completed";
            case TaskStatus::Cancelled: return " Cancelled";
            default: return " Unknown";
        }
    }
}
References Cancelled, Completed, InProgress, and Pending.
Referenced by App::handleRecent().
isValidPriority()
bool isValidPriority (int priority) consteval
Validates priority value at compile time.
C++23 Feature: consteval functions for compile-time validation
Parameters
priority The priority value to validate
Returns
true if the priority is valid (0-10)
Definition at line 388 of file task.h.
{
    return priority >= 0 && priority <= 10;
}
isValidTaskId()
bool isValidTaskId (int id) consteval
Validates task ID at compile time.
C++23 Feature: consteval function for compile-time validation
Parameters
id The task ID to validate
Returns
true if the ID is valid (positive)
Definition at line 398 of file task.h.
{
    return id > 0;
}
jsonErrorToString()
std::string jsonErrorToString (JsonError error)
Convert a JsonError enum to its string representation.
Parameters
error The error to convert
Returns
String representation of the error
Convert a JsonError enum to its string representation.
Parameters
error The JSON error code
Returns
Human-readable error message
Definition at line 158 of file task.cpp.
{
    switch (error) {
        case JsonError::FileNotFound: return "JSON file not found";
        case JsonError::InvalidFormat: return "Invalid JSON format";
        case JsonError::WriteError: return "Failed to write JSON file";
        case JsonError::ParseError: return "Failed to parse JSON";
        default: return "Unknown JSON error";
    }
}
References FileNotFound, InvalidFormat, ParseError, and WriteError.
maxTaskDescriptionLength()
size_t maxTaskDescriptionLength () consteval
Maximum allowed length for task descriptions.
C++23 Feature: consteval and uz suffix for size_t
Returns
Maximum description length (500)
Definition at line 416 of file task.h.
{
    return 500uz;
}
Referenced by validateTaskData().
maxTaskTitleLength()
size_t maxTaskTitleLength () consteval
Maximum allowed length for task titles.
C++23 Feature: consteval and uz suffix for size_t
Returns
Maximum title length (100)
Definition at line 407 of file task.h.
{
    return 100uz;  // C++23: uz suffix for size_t
}
Referenced by validateTaskData().
serializeTaskToJson()
JsonResult serializeTaskToJson (const Task & task, const std::string & filePath)
Serialize a task to a JSON file.
Parameters
task The task to serialize
filePath Path to the output file
Returns
JsonResult indicating success or the reason for failure
stringToTaskStatus()
std::optional< TaskStatus > stringToTaskStatus (const std::string & str)
Convert a string to a TaskStatus enum.
Parameters
str The string to convert
Returns
TaskStatus if valid, nullopt if invalid
Convert a string to a TaskStatus enum.
Parameters
str The string to convert
Returns
TaskStatus if valid, nullopt if invalid
Case-insensitive and handles common status name variations
Definition at line 414 of file task.cpp.
{
    if (str == "pending" || str == "Pending") return TaskStatus::Pending;
    if (str == "progress" || str == "in-progress" || str == "In Progress" || str == "InProgress") return TaskStatus::InProgress;
    if (str == "completed" || str == "Completed") return TaskStatus::Completed;
    if (str == "cancelled" || str == "Cancelled") return TaskStatus::Cancelled;
    return std::nullopt;
}
References Cancelled, Completed, InProgress, and Pending.
Referenced by Task::fromJson().
taskErrorToString()
std::string taskErrorToString (TaskError error)
Convert a TaskError enum to its string representation.
Parameters
error The error to convert
Returns
String representation of the error
Convert a TaskError enum to its string representation.
Parameters
error The error to convert
Returns
Human-readable error message
Definition at line 427 of file task.cpp.
{
    switch (error) {
        case TaskError::InvalidId: return "Invalid task ID";
        case TaskError::TaskNotFound: return "Task not found";
        case TaskError::InvalidStatus: return "Invalid task status";
        case TaskError::EmptyTitle: return "Task title cannot be empty";
        case TaskError::DuplicateTask: return "Task with this title already exists";
        case TaskError::InvalidPriority: return "Priority must be between 0 and 10";
        default: return "Unknown error";
    }
}
References DuplicateTask, EmptyTitle, InvalidId, InvalidPriority, InvalidStatus, and TaskNotFound.
taskStatusToString()
std::string taskStatusToString (TaskStatus status)
Convert a TaskStatus enum to its string representation.
Parameters
status The status to convert
Returns
String representation of the status
Convert a TaskStatus enum to its string representation.
Parameters
status The status to convert
Returns
String representation of the status
Definition at line 398 of file task.cpp.
{
    switch (status) {
        case TaskStatus::Pending: return "Pending";
        case TaskStatus::InProgress: return "In Progress";
        case TaskStatus::Completed: return "Completed";
        case TaskStatus::Cancelled: return "Cancelled";
        default: return "Unknown";
    }
}
References Cancelled, Completed, InProgress, and Pending.
Referenced by App::handlePriority(), App::handleSort(), TaskManager::listTasks(), TaskManager::listTasksByStatus(), Task::to_string(), and Task::toJson().
unescapeJsonString()
std::string unescapeJsonString (const std::string & str)
Unescape a JSON string.
Parameters
str The JSON string to unescape
Returns
Unescaped string
Unescape a JSON string.
Parameters
str The JSON string to unescape
Returns
Unescaped string
Definition at line 206 of file task.cpp.
{
    std::string unescaped;
    unescaped.reserve(str.size());
    for (size_t i = 0; i < str.size(); ++i) {
        if (str[i] == '\\' && i + 1 < str.size()) {
            switch (str[i + 1]) {
                case '"': unescaped += '"'; ++i; break;
                case '\\': unescaped += '\\'; ++i; break;
                case 'b': unescaped += '\b'; ++i; break;
                case 'f': unescaped += '\f'; ++i; break;
                case 'n': unescaped += '\n'; ++i; break;
                case 'r': unescaped += '\r'; ++i; break;
                case 't': unescaped += '\t'; ++i; break;
                default: unescaped += str[i]; break;
            }
        } else {
            unescaped += str[i];
        }
    }
    return unescaped;
}
Referenced by Task::fromJson().
validateTaskData()
bool validateTaskData (std::string_view title, std::string_view description, int priority) constexpr
Validate task data fields.
C++23 Feature: if consteval for performance optimization with different behavior at compile-time vs runtime
Parameters
title The task title to validate
description The task description to validate
priority The priority value to validate
Returns
true if all data is valid
Definition at line 458 of file task.h.
{
    if consteval {
        // Compile-time validation (basic checks)
        return !title.empty() &&
               title.length() <= maxTaskTitleLength() &&
               description.length() <= maxTaskDescriptionLength() &&
               priority >= 0 && priority <= 10;  // Direct check instead of consteval call
    } else {
        // Runtime validation (more comprehensive)
        if (title.empty()) return false;
        if (title.length() > maxTaskTitleLength()) return false;
        if (description.length() > maxTaskDescriptionLength()) return false;
        if (priority < 0 || priority > 10) return false;  // Direct check
        // Runtime-only checks
        if (title.front() == ' ' || title.back() == ' ') return false;
        return true;
    }
}
References maxTaskDescriptionLength(), and maxTaskTitleLength().