Task Tracker CLI: task.cpp File Reference
task.cpp File Reference
Implementation of Task class and related utility functions.
#include "task.h"
#include "task_manager.h"
#include <iostream>
#include <iomanip>
#include <sstream>
Functions
std::string escapeJsonString (const std::string &str)
Escape special characters in a string for JSON encoding.
std::chrono::system_clock::time_point isoStringToTimePoint (const std::string &iso_str)
Parse ISO 8601 formatted string to time_point.
std::string jsonErrorToString (JsonError error)
Convert JSON error enum to string.
std::optional< TaskStatus > stringToTaskStatus (const std::string &str)
Convert string to TaskStatus enum.
std::string taskErrorToString (TaskError error)
Convert TaskError enum to string representation.
std::string taskStatusToString (TaskStatus status)
Convert TaskStatus enum to string representation.
std::string timePointToIsoString (const std::chrono::system_clock::time_point &tp)
Convert time_point to ISO 8601 formatted string.
std::string unescapeJsonString (const std::string &str)
Unescape JSON string by converting escape sequences to characters.
Detailed Description
Implementation of Task class and related utility functions.
Contains the implementation of Task methods, JSON serialization, and utility functions for task management.
Definition in file task.cpp.
Function Documentation
escapeJsonString()
std::string escapeJsonString (const std::string & str)
Escape special characters in a string for JSON encoding.
Parameters
str The input string to escape
Returns
JSON-safe escaped string
Handles quotes, backslashes, control characters, and UTF-8
Definition at line 174 of file task.cpp.
{
    std::string escaped;
    escaped.reserve(str.size() + 20); // Reserve some extra space for escapes
    for (unsigned char c : str) {
        switch (c) {
            case '"': escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b"; break;
            case '\f': escaped += "\\f"; break;
            case '\n': escaped += "\\n"; break;
            case '\r': escaped += "\\r"; break;
            case '\t': escaped += "\\t"; break;
            default:
                // Only escape actual control characters (0-31), not UTF-8 bytes
                if (c < 32) {
                    escaped += std::format("\\u{:04x}", c);
                } else {
                    // For UTF-8 and normal ASCII (32-255), keep as-is
                    escaped += static_cast<char>(c);
                }
                break;
        }
    }
    return escaped;
}
Referenced by Task::toJson().
isoStringToTimePoint()
std::chrono::system_clock::time_point isoStringToTimePoint (const std::string & iso_str)
Parse ISO 8601 formatted string to time_point.
Parameters
iso_str The ISO 8601 string to parse
Returns
Corresponding time_point
Handles millisecond precision if present
Definition at line 251 of file task.cpp.
{
    std::tm tm = {};
    std::istringstream ss(iso_str);
    ss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%S");
    auto tp = std::chrono::system_clock::from_time_t(std::mktime(&tm));
    // Handle milliseconds if present
    auto dot_pos = iso_str.find('.');
    if (dot_pos != std::string::npos) {
        auto ms_str = iso_str.substr(dot_pos + 1, 3);
        if (!ms_str.empty() && std::isdigit(ms_str[0])) {
            int ms = std::stoi(ms_str);
            tp += std::chrono::milliseconds(ms);
        }
    }
    return tp;
}
Referenced by Task::fromJson().
jsonErrorToString()
std::string jsonErrorToString (JsonError error)
Convert JSON error enum to string.
Convert a JsonError enum to its string representation.
Parameters
error The JSON error code
Returns
Human-readable error message
Definition at line 158 of file task.cpp.
{
    switch (error) {
        case JsonError::FileNotFound: return "JSON file not found";
        case JsonError::InvalidFormat: return "Invalid JSON format";
        case JsonError::WriteError: return "Failed to write JSON file";
        case JsonError::ParseError: return "Failed to parse JSON";
        default: return "Unknown JSON error";
    }
}
References FileNotFound, InvalidFormat, ParseError, and WriteError.
stringToTaskStatus()
std::optional< TaskStatus > stringToTaskStatus (const std::string & str)
Convert string to TaskStatus enum.
Convert a string to a TaskStatus enum.
Parameters
str The string to convert
Returns
TaskStatus if valid, nullopt if invalid
Case-insensitive and handles common status name variations
Definition at line 414 of file task.cpp.
{
    if (str == "pending" || str == "Pending") return TaskStatus::Pending;
    if (str == "progress" || str == "in-progress" || str == "In Progress" || str == "InProgress") return TaskStatus::InProgress;
    if (str == "completed" || str == "Completed") return TaskStatus::Completed;
    if (str == "cancelled" || str == "Cancelled") return TaskStatus::Cancelled;
    return std::nullopt;
}
References Cancelled, Completed, InProgress, and Pending.
Referenced by Task::fromJson().
taskErrorToString()
std::string taskErrorToString (TaskError error)
Convert TaskError enum to string representation.
Convert a TaskError enum to its string representation.
Parameters
error The error to convert
Returns
Human-readable error message
Definition at line 427 of file task.cpp.
{
    switch (error) {
        case TaskError::InvalidId: return "Invalid task ID";
        case TaskError::TaskNotFound: return "Task not found";
        case TaskError::InvalidStatus: return "Invalid task status";
        case TaskError::EmptyTitle: return "Task title cannot be empty";
        case TaskError::DuplicateTask: return "Task with this title already exists";
        case TaskError::InvalidPriority: return "Priority must be between 0 and 10";
        default: return "Unknown error";
    }
}
References DuplicateTask, EmptyTitle, InvalidId, InvalidPriority, InvalidStatus, and TaskNotFound.
taskStatusToString()
std::string taskStatusToString (TaskStatus status)
Convert TaskStatus enum to string representation.
Convert a TaskStatus enum to its string representation.
Parameters
status The status to convert
Returns
String representation of the status
Definition at line 398 of file task.cpp.
{
    switch (status) {
        case TaskStatus::Pending: return "Pending";
        case TaskStatus::InProgress: return "In Progress";
        case TaskStatus::Completed: return "Completed";
        case TaskStatus::Cancelled: return "Cancelled";
        default: return "Unknown";
    }
}
References Cancelled, Completed, InProgress, and Pending.
Referenced by App::handlePriority(), App::handleSort(), TaskManager::listTasks(), TaskManager::listTasksByStatus(), Task::to_string(), and Task::toJson().
timePointToIsoString()
std::string timePointToIsoString (const std::chrono::system_clock::time_point & tp)
Convert time_point to ISO 8601 formatted string.
Parameters
tp The time point to convert
Returns
ISO 8601 formatted string (YYYY-MM-DDTHH:MM:SS.mmm)
Definition at line 234 of file task.cpp.
{
    auto time_t = std::chrono::system_clock::to_time_t(tp);
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(tp.time_since_epoch()) % 1000;
    std::ostringstream oss;
    // Fix: Use localtime instead of gmtime to show local timezone
    oss << std::put_time(std::localtime(&time_t), "%Y-%m-%dT%H:%M:%S");
    oss << std::format(".{:03d}", ms.count()); // Remove Z suffix for local time
    return oss.str();
}
Referenced by Task::toJson().
unescapeJsonString()
std::string unescapeJsonString (const std::string & str)
Unescape JSON string by converting escape sequences to characters.
Unescape a JSON string.
Parameters
str The JSON string to unescape
Returns
Unescaped string
Definition at line 206 of file task.cpp.
{
    std::string unescaped;
    unescaped.reserve(str.size());
    for (size_t i = 0; i < str.size(); ++i) {
        if (str[i] == '\\' && i + 1 < str.size()) {
            switch (str[i + 1]) {
                case '"': unescaped += '"'; ++i; break;
                case '\\': unescaped += '\\'; ++i; break;
                case 'b': unescaped += '\b'; ++i; break;
                case 'f': unescaped += '\f'; ++i; break;
                case 'n': unescaped += '\n'; ++i; break;
                case 'r': unescaped += '\r'; ++i; break;
                case 't': unescaped += '\t'; ++i; break;
                default: unescaped += str[i]; break;
            }
        } else {
            unescaped += str[i];
        }
    }
    return unescaped;
}
Referenced by Task::fromJson().